services:
  # Service API FastAPI
  - type: web
    name: taskmaster-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: taskmaster-db
          property: connectionString

databases:
  - name: taskmaster-db
    databaseName: taskmaster
    user: taskmaster_user
